class Categories {
  static final Map<String, List<String>> data = {
    "music": [
      "Alternative",
      "Blues",
      "Christian and gospel",
      "Classical",
      "Country",
      "Dance",
      "DJs",
      "Electronic",
      "Hip hop and rap",
      "Indie spotlight",
      "Jazz",
      "Latino",
      "Metal",
      "Music news and general info",
      "Pop",
      "R&B and soul",
      "Reggae",
      "Rock",
      "Talk radio",
      "Venues",
      "World",
    ],
    "hobby": [
      "Arts and crafts",
      "Astrology",
      "Birdwatching",
      "Boating",
      "Cartoons",
      "Celebrity fan and gossip",
      "Chess",
      "Cigars",
      "Comedy",
      "Dance",
      "Design",
      "Drawing and sketching",
      "Exercise and fitness",
      "Freelance writing",
      "Gambling",
      "Genealogy",
      "Guitar",
      "Jewelry making",
      "Modeling",
      "Needlework",
      "Painting",
      "Paranormal phenomena",
      "Performance arts",
      "Photography",
      "Sci-fi and fantasy",
      "Scrapbooking",
      "Screenwriting",
      "Shopping",
      "Stamps and coins",
    ],
    "movies": [
      "Action and adventure",
      "Animation",
      "Bollywood",
      "Business and news",
      "Comedy",
      "Documentary",
      "Drama",
      "Foreign",
      "Horror",
      "Independent",
      "Movie news and general info",
      "Music",
      "Reality TV",
      "Romance",
      "Sci-fi and fantasy",
      "Sports themed",
    ],
    "finance": [
      "Banking",
      "Beginning investing",
      "Credit, debt, and loans",
      "Financial news",
      "Financial planning",
      "Hedge funds",
      "Insurance",
      "Investing",
      "Mortgage",
      "Mutual funds",
      "Options",
      "Real estate",
      "Retirement planning",
      "Stocks",
      "Tax planning",
    ],
    "sports": [
      "Action sports",
      "Auto racing",
      "Baseball",
      "Bodybuilding",
      "Boxing",
      "Canoeing and kayaking",
      "Climbing",
      "College basketball",
      "College football",
      "Cricket",
      "Cycling",
      "Fantasy sports",
      "Figure skating",
      "Fishing",
      "Golf",
      "Horse racing",
      "Hunting and shooting",
      "Ice hockey",
      "Martial arts",
      "Mountain biking",
      "NASCAR racing",
      "NBA basketball",
      "NFL football",
      "Olympics",
      "Paintball",
      "Poker",
      "Power and motorcycles",
      "Rodeo",
      "Rugby",
      "Running and jogging",
      "Sailing",
      "Scuba diving",
      "Skateboarding",
      "Skiing",
      "Snowboarding",
      "Soccer",
      "Sporting goods",
      "Sports news",
      "Surfing and bodyboarding",
      "Swimming",
      "Table tennis and ping-pong",
      "Tennis",
      "Volleyball",
      "Waterskiing and wakeboarding",
    ],
    "technology": [
      "Animation",
      "Antivirus",
      "Cameras and camcorders",
      "Cell phones",
      "Computer certification",
      "Computer networking",
      "Computer programming",
      "Computer reviews",
      "Data centers",
      "Databases",
      "Enterprise software",
      "Graphics software",
      "Home entertainment",
      "Linux",
      "MacOS",
      "Mobile",
      "Network security",
      "Open source",
      "PC support",
      "SEO",
      "Startups",
      "Tablets",
      "Tech news",
      "Video conferencing",
      "Web design",
      "Windows",
    ]
  };
}
