// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg3DqvZUbMaEIGXpsWBHWomRAXS6i10kY',
    appId: '1:382692183595:web:d838435f925dfde356a46e',
    messagingSenderId: '382692183595',
    projectId: 'tiktok-flutter-raymond',
    authDomain: 'tiktok-flutter-raymond.firebaseapp.com',
    storageBucket: 'tiktok-flutter-raymond.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAQqoHMqIVDGUALlm3s8din6vOCC4tCl4',
    appId: '1:382692183595:android:200f06dbb38eca9f56a46e',
    messagingSenderId: '382692183595',
    projectId: 'tiktok-flutter-raymond',
    storageBucket: 'tiktok-flutter-raymond.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjg_Azw_52ftyU0B2pedw8w0HSldYWYjg',
    appId: '1:382692183595:ios:bb82310d58d2132e56a46e',
    messagingSenderId: '382692183595',
    projectId: 'tiktok-flutter-raymond',
    storageBucket: 'tiktok-flutter-raymond.appspot.com',
    iosBundleId: 'com.raymond.thread',
  );
}
