// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH33zKGeBaWHATiWcz-Pc6ptntWftxVAo',
    appId: '1:356568245641:web:edf1fb2f00959f20322d58',
    messagingSenderId: '356568245641',
    projectId: 'thread-flutter-raymond',
    authDomain: 'thread-flutter-raymond.firebaseapp.com',
    storageBucket: 'thread-flutter-raymond.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCegukGgAoQxpA9t8JDUIePbc-imQpda9c',
    appId: '1:356568245641:android:415e77b2409bbe8b322d58',
    messagingSenderId: '356568245641',
    projectId: 'thread-flutter-raymond',
    storageBucket: 'thread-flutter-raymond.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFrHAoPZRs9mR3ZQ7VijDT6tpMsZrRkGg',
    appId: '1:356568245641:ios:f544ed89ef873693322d58',
    messagingSenderId: '356568245641',
    projectId: 'thread-flutter-raymond',
    storageBucket: 'thread-flutter-raymond.appspot.com',
    iosBundleId: 'com.raymond.thread',
  );
}
